name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
            cd /var/www/html/todo-backend || exit 1
            sudo git fetch origin
            sudo git reset --hard origin/main
            sudo npm install --production
            sudo pm2 restart backend || sudo pm2 start npm --name "backend" -- start